load("@build_bazel_rules_swift//swift:swift.bzl", "swift_test")

swift_test(
    name = "SwiftDemangleTests",
    srcs = [
        "SwiftDemangleTests.swift",
    ],
    deps = [
        "//:SwiftDemangle",
    ],
)
